default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: db/development
  host: localhost

test:
  <<: *default
  database: test


production:
  <<: *default
  database: party_planner
  username: party_Planner
  password: <%= ENV['PARTY_PLANNER_DATABASE_PASSWORD'] %>
