default: &default
  adapter: postgresql
  database: db/development
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: Party_Planner_development

test:
  <<: *default
  database: Party_Planner_test


production:
  <<: *default
  database: Party_Planner_production
  # username: Party_Planner
  # password: <%= ENV['PARTY_PLANNER_DATABASE_PASSWORD'] %>
