default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432
  # username: dev
  # password: dev

development:
  <<: *default
  database: db/development
  host: localhost

test:
  <<: *default
  database: db/test


production:
  <<: *default
  database: Party_planner
  # username: Party_Planner
  # password: <%= ENV['PARTY_PLANNER_DATABASE_PASSWORD'] %>
